proStage_accueil:
    path: /
    controller: App\Controller\ProStageController::afficherAccueil

proStage_entreprises:
    path: /entreprises
    controller: App\Controller\ProStageController::afficherEntreprises

proStage_entreprise:
    path: /entreprise/{nomEntreprise}
    controller: App\Controller\ProStageController::entreprise

proStage_formations:
    path: /formations
    controller: App\Controller\ProStageController::afficherFormations

proStage_formation:
    path: /formation/{nomFormation}
    controller: App\Controller\ProStageController::formation

proStage_descriptifStage:
    path: /stage/{id}
    controller: App\Controller\ProStageController::afficherDescriptifStage

proStage_ajoutEntreprise:
    path: admin/ajouterModifierEntreprise
    controller: App\Controller\ProStageController::ajouterEntreprise

proStage_modificationEntreprise:
    path: admin/ajouterModifierEntreprise/{id}
    controller: App\Controller\ProStageController::modifierEntreprise

proStage_ajoutStage:
    path: user/ajouterStage
    controller: App\Controller\ProStageController::ajouterStage

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_inscription:
    path: /inscription
    controller: App\Controller\SecurityController::inscription
