proStage_accueil:
    path: /
    controller: App\Controller\ProStageController::afficherAccueil

proStage_entreprises:
    path: /entreprises
    controller: App\Controller\ProStageController::afficherEntreprises

proStage_entreprise:
    path: /entreprise/{nomEntreprise}
    controller: App\Controller\ProStageController::entreprise

proStage_formations:
    path: /formations
    controller: App\Controller\ProStageController::afficherFormations

proStage_formation:
    path: /formation/{nomFormation}
    controller: App\Controller\ProStageController::formation

proStage_descriptifStage:
    path: /stage/{id}
    controller: App\Controller\ProStageController::afficherDescriptifStage
